### ISSUE TITLE
pretrained model link failed

### ISSUE THREAD

**Issue by chinchia** [hellojialee/Improved-Body-Parts#21]
Can you reupload the pretrained model PoseNet_52_epoch.pth?
Seems like the link was failed.

**Comment by jialee93** [comment]
Hi, I have check the download link and it is still fine.

**Comment by chinchia** [comment]
I tried "BaiduCloud" link again but it still failed. It told me that the page is no longer existed. Not sure if it was my Internet problem. Can you upload the pretrained model to GoogleDrive or other platform?

**Comment by jialee93** [comment]
Hi, the GoogleDrive link in README is still there. I past it as follow:
https://drive.google.com/open?id=1gLa2oNxnbFPo0BjnpPaiAmWJwyND8wkA

**Comment by chinchia** [comment]
Oh, yeah, I had downloaded that already. But the link only provides pre-trained model "without" optimizer. And I guess that the link in Baidu is pre-trained model "with" optimizer. Or if I misunderstood it? Are they the same pretrained model?

**Comment by jialee93** [comment]
Yes, you are right. It' OK if you continue to train with the pre-trained network parameters only.

**Comment by chinchia** [comment]
OK, then I will just try with it. Thanks for explanation.
