### ISSUE TITLE
Where is the coco_train_dataset512.h5 file?

### ISSUE THREAD

**Issue by FanShuixing** [hellojialee/Improved-Body-Parts#22]
Hi,Thanks for your great work.I have a question about the coco_train_dataset512.h5 file which is need to train model.Where can I download it?
![image](https://user-images.githubusercontent.com/35692924/81380130-e8526280-913c-11ea-9fe9-89d16bd80357.png)

**Comment by jialee93** [comment]
Hi friend, coco_train_dataset512.h5 is generated by the script data/coco_masks_hdf5.py. Alternatively, you can rewrite the data loader part reading from the raw images directly.

**Comment by Sunstin** [comment]
Hi,what is the file coco_train_dataset384.h5 in code coco_masks_hdf5.py? Does it need to download or other way to have it?

**Comment by Sunstin** [comment]
after I put the coco data under the file, code is successfully running now. But l want to konw why, so i'm reading the code.Why you choose to load the data by create h5 file? @hellojialee Thanks

**Comment by hellojialee** [comment]
It is actually a legacy manner borrower from other referred repo (keras/tf). Using the hdf5 file can accelerate the data preparation, and we can read and write the hdf5 file in a multi-process in a dataloader Class. I rewrite the dataloader part by reading the raw image data and still achieve high I/O efficiency and GPU utilization. You can refer to other released repo. And I will post this part in the future.

**Comment by Sunstin** [comment]
Thank you very much for your reply~~
