### ISSUE TITLE
How to use train.py to run

### ISSUE THREAD

**Issue by Sunstin** [hellojialee/Improved-Body-Parts#24]
because my computer don't have GPU,so i should run train.py. What  request should i give in terminal? I tried but faild. @hellojialee Thank you very much~

**Comment by Sunstin** [comment]
python train.py

**Comment by hellojialee** [comment]
Hi, my friend. I'm sorry to tell you the python script train.py only supports GPU training. Or you can try to convert the GUP pre-trained model into a CPU model and change the code that only considers GPU usage cases. I highly recommend GPU training. CPU training is only suitable for those work concentrated on model compression or light-weighted backbones.

**Comment by Sunstin** [comment]
i'm trying to solve these problems,thank you for you advice~~
