### ISSUE TITLE
A small question about the formulation (2) 

### ISSUE THREAD

**Issue by Elody-07** [hellojialee/Improved-Body-Parts#25]
Hi, thanks for sharing your brilliant work. I noticed that when computing Sd, the two formulations are all close to 1 ( the first line when S ~= 1, Sd ~= 0.9, the second line when S ~= 0.01, Sd ~= 0.97). How does Sd balance easy and hard samples?

**Comment by hellojialee** [comment]
Hi @Elody-07, I guess you have already figured it out. In your case, it is the scaling factor term that compresses the easy foreground and background.
