### ISSUE TITLE
Aboat fig 4 is or not improved hourglass ?

### ISSUE THREAD

**Issue by zouxuelian** [hellojialee/Improved-Body-Parts#26]
Hello, your work is excellent, but there is one thing I don’t understand very well. Figure 4 in the paper is an improved hourglass network, but in Figure 3, it is still marked as hourglass, and you don’t see the part about Figure 4 in your code. Code. Excuse me, I don’t know if I misunderstood Figure 4.

**Comment by hellojialee** [comment]
Hi @zouxuelian, thank you for your interest!
Figure 4 seems not novel at all and its structure is not optimal,  **it intends more to shows where we apply the supervision** of ground truth (attention) heatmaps, and indicates the heatmap channel numbers. The improved components of the network refer to identity mappings, spatial attention, and channel attention. For example, you can find the shortcuts here:
https://github.com/hellojialee/Improved-Body-Parts/blob/f2b673f835c6f354fe14b00df824613e599f9ea5/models/posenet.py#L98

**The code of Figure 4**, A.K.A, first-order hourglass module can be found here:
https://github.com/hellojialee/Improved-Body-Parts/blob/f2b673f835c6f354fe14b00df824613e599f9ea5/models/layers_transposed.py#L12
and here
https://github.com/hellojialee/Improved-Body-Parts/blob/f2b673f835c6f354fe14b00df824613e599f9ea5/models/layers_transposed.py#L248
I also use a recursive trick to build hourglass, thus it is not so easy to find.

Hope my reply can help you. For more structure information, I recommend this picture for you:
![IMHN](https://github.com/sokunmin/Improved-Body-Parts/blob/master/visual/network_details.png)
)

**Comment by zouxuelian** [comment]
Thank you very much for your answer, it helped me a lot. I will read the code link you gave, thank you
