### ISSUE TITLE
how to divide different people's kp in the same image?

### ISSUE THREAD

**Issue by gonghaotian** [hellojialee/Improved-Body-Parts#28]
你好，我之前在学习CornerNet，CenterNet时，不同目标的相同关键点是通过嵌入向量分组的，如83channel=80类+嵌入向量+xy偏移量，所以当图片中有多个人时，IMHN的输出是如何解析的？IMHN的输出是什么样的，通道有什么含义？我理解的是所有人体的同个关键点预测在同张heatmap上，这样如何区分不同人呢？谢谢

**Comment by gonghaotian** [comment]
我注意到demo中使用了PAF，所以网络输出的通道中一部分是PAF向量场的预测？我在论文中没有找到相关解释

**Comment by gonghaotian** [comment]
重新理解了下，输出的关键点是通过（K,K+P）预测的PAF连接的，但是输出的通道是什么样的还是不太理解

**Comment by hellojialee** [comment]
Yes, your first comment is right. Feel free to propose your issues.
The body part responses between adjacent keypoints are used as the paring information to greedily group the keypoints into individual human poses.

**Comment by soans1994** [comment]
> Yes, your first comment is right. Feel free to propose your issues.
> The body part responses between adjacent keypoints are used as the paring information to greedily group the keypoints into individual human poses.

@hellojialee 

can you please tell me how to draw ellipse shape heatmap? Compared to key point heatmap what else data is needed ?
2 key points and width? That’s all?
