### ISSUE TITLE
make_mask中一定要有mask信息？

### ISSUE THREAD

**Issue by StriveForC** [hellojialee/Improved-Body-Parts#29]
作者你好，在转coco信息的时候，一定要mask信息，不知作者在用MPII数据的时候是怎么处理的，有没有脚本呢？

**Comment by hellojialee** [comment]
Maybe this can help, please have a look at here: [How to generate mask images for MPI dataset](https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation/issues/166)

Alternatively, you can try to supervise the association info only in labeled ground-truth areas but you'd better supervise the whole image when it comes to keypoint info.
