### ISSUE TITLE
further improvements in speed and maintaining high accuracy

### ISSUE THREAD

**Issue by thancaocuong** [hellojialee/Improved-Body-Parts#32]
Hi, nice work. But I have some recommendations to further improve the speed and maintaining high accuracy.
1, Optimize the post-processing speed (write in C++)
2, Try Knowledge distillation (currently I think we could reduce 70 -> 80% size of the model with comparable accuracy).
3, Try TensorRT.
But first I think you need to clean the source code architecture so that everyone could easy to help you.

**Comment by hellojialee** [comment]
Yes, I can't agree with you more.  I prefer to reformat the post-processing in a multi-processing way currently. Sorry for my messy project only for the earlier paper publication.  And I plan to release a simplified and neat code. I will remember your suggestions.  Thank you so much :)
