### ISSUE TITLE
IndentationError in py_cocodata_server/py_data_transformer.py

### ISSUE THREAD

**Issue by WangChen100** [hellojialee/Improved-Body-Parts#34]
Hi, it appears IndentationError in line 59 of py_cocodata_server/py_data_transformer.py

` (width, weight) = center`

The first space be removed.

**Comment by WangChen100** [comment]
![image](https://user-images.githubusercontent.com/30588895/103991694-0392d780-51ce-11eb-8c66-4cd9464dca71.png)

**Comment by hellojialee** [comment]
Thank you for pointing this out! Fixed it.  I should release a clean repo and I will.
