### ISSUE TITLE
issue with python demo_image.py and python evaluate.py

### ISSUE THREAD

**Issue by manishkth** [hellojialee/Improved-Body-Parts#47]

**Comment by hellojialee** [comment]
Hi friend, what's your issue?

**Comment by manishkth** [comment]
hi when I tried to run "python demo.py
![image](https://user-images.githubusercontent.com/17065395/128665520-a59ae584-6356-4da3-b9c4-59ca49fcee87.png)

getting an error as shown below
![image](https://user-images.githubusercontent.com/17065395/128665589-223a1da0-c3be-4b8d-b739-9c44e3a6c9dd.png)
