### ISSUE TITLE
It can be Running in Ubuntu18.04 with RTX3080, CUDA11.1？

### ISSUE THREAD

**Issue by A7777-gp** [hellojialee/Improved-Body-Parts#48]
Thank your wonderful work，I downloaded your code and tried to run it.But I encountered a lot of errors when downloading the packages.Can this run on Ubuntu18.04, RTX3080?

**Comment by hellojialee** [comment]
Hi，I haven't gave it a try. Still, it should work on Ubuntu18.04, RTX3080 with proper settings.

**Comment by A7777-gp** [comment]
When I was downloading the package, some of the versions could not be downloaded. For example, apex=0.1, netron==2.9.4

**Comment by hellojialee** [comment]
Sorry my fault. Just ignore netron. As for Nvidia Apex, you can install it manually according to the instruction on https://github.com/NVIDIA/apex.
