### ISSUE TITLE
Data pre-processing

### ISSUE THREAD

**Issue by A7777-gp** [hellojialee/Improved-Body-Parts#51]
Thank you for a job well done! I have some doubts like you ask，In the data pre-processing,Why is there a problem with center point alignment？Is this because the size of the input image through CNN has changed?

**Comment by hellojialee** [comment]
https://zhuanlan.zhihu.com/p/109118177
https://discuss.pytorch.org/t/what-we-should-use-align-corners-false/22663/9

**Comment by A7777-gp** [comment]
heartfelt thanks!!!
