### ISSUE TITLE
With python demo_image.py

### ISSUE THREAD

**Issue by A7777-gp** [hellojialee/Improved-Body-Parts#52]
Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Warning:  multi_tensor_applier fused unscale kernel is unavailable, possibly because apex was installed without --cuda_ext --cpp_ext. Using Python fallback.  Original ImportError was: ModuleNotFoundError("No module named 'amp_C'",)
start processing...
Traceback (most recent call last):
  File "demo_image.py", line 637, in <module>
    params, model_params = config_reader()
  File "/scratch/gp/Improved-Body-Parts-master/utils/config_reader.py", line 9, in config_reader
    param = config['param']  # 继承了dict的一种字典类型
  File "/scratch/mool/ana3/envs/gpp/lib/python3.6/site-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'param'
(gpp) zhhu@k8s-master01:/scratch/gp/Improved-Body-Parts-master$ python demo_image.py
I am in ubuntu18.04 CUDA10.0 run it.But it failed.can you help me to watch the errror? thanks!!!

**Comment by hellojialee** [comment]
Install Apex from source:
`git clone https://github.com/NVIDIA/apex
cd apex
pip install -v --disable-pip-version-check --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./`

**Comment by A7777-gp** [comment]
Thank you very much for your answer！I re-downloaded Apex and it still didn't work,Is this error a code error?

**Comment by hellojialee** [comment]
Yes, you're right. I suggest to debug this function line by line first:
https://github.com/hellojialee/Improved-Body-Parts/blob/d6fc00caaa0de4f2c89f8673c269ccbb675bbbdf/utils/config_reader.py#L6

**Comment by A7777-gp** [comment]
why i can run this code successfully in windows10, but failed in ubuntu18.04? I used the same python vision. I am so sad!!!

**Comment by A7777-gp** [comment]
I tried to modify the code, but it still didn't work on Ubuntu.

**Comment by hellojialee** [comment]
Have you fixed it? This project is developed on Ubuntu.

**Comment by wjk13720041** [comment]
You can try changing " config = ConfigObj('/home/jia/Desktop/Improved-Body-Parts/utils/config') " to " config = ConfigObj('./utils/config') " in line 8
